#language: es
Característica: Como usuario administrador del backoffice quiero editar un beneficio

    Antecedentes:
        Dado estoy en "/backoffice/signin"
        Y relleno "_username" con "apibackofficetester"
        Y relleno "_password" con "apitesterbackoffice"
        Y presiono "_submit"
        Y sigo "Beneficios Corporativos"
        Y espero a que aparezca el contenido dinámico "Listado de Comercios" en ".breadcrumb"
        Y espero a que aparezca el contenido dinámico "45 minutos" en ".backgrid-company-list"
        Y relleno "filters[name]" con "A Fondo"
        Y hago click en "#name-filter-btn-submit"
        Entonces espero a que aparezca el contenido dinámico "A Fondo" en ".backgrid-company-list"
        Cuando sigo "A Fondo"
        Y espero a que aparezca el contenedor dinámico ".company-view-container"
        Entonces el breadcrumb debe ser "Beneficios Corporativos > Listado de Comercios > A Fondo"

    @javascript @loadBenefitsBenefitData
    Escenario: Editar beneficio con sucursales adheridas
        Dado espero a que aparezca el contenido dinámico "officia" en "#benefits"
        Y hago click y sigo "#benefits tr:contains(officia) .action-icon"
        Y espero a que aparezca el contenedor dinámico ".benefit-form"
        Y tildo el checkbox "active"
        Y relleno "owner" con "Marina Sucari"
        Y relleno "name" con "BNF > Todos los lues"
        Y selecciono "10%" de "discount"
        Y selecciono "General" de "targetUserType"
        Y relleno la fecha "validFrom" con "01/12/2013"
        Y marco "expires"
        Y relleno la fecha "validUntil" con "01/12/2014"
        Y hago click en "#ms-redeemingMethods .ms-selectable li:eq(1)"
        Y hago click en "#ms-paymentMethods .ms-selectable li:eq(0)"
        Y hago click en "#ms-paymentMethods .ms-selectable li:eq(2)"
        Y relleno "title" con "10% de descuento en la compra de..."
        Y lleno el WYSIWYG "description" con "En la compra de zapatillas te hacemos un 10%"
        Y agrego tag "zapatillas" en el elemento "#tag-input"
        Y agrego tag "deportes" en el elemento "#tag-input"
        Y agrego tag "correr" en el elemento "#tag-input"
        Y agrego tag "zapatillas para correr" en el elemento "#tag-input"
        Y hago click en "#ms-categories .ms-selectable li:eq(1)"
        Cuando hago click en "button:contains(Guardar)"
        Entonces espero a que aparezca el contenido dinámico "Activación del Beneficio" en ".modal-title"
        Y hago click en "button:contains(Confirmar)"
        Y espero a que cambie la URL
        Y la URL debe seguir el patrón "/backoffice/benefits/benefit/\d+/view"

    @javascript @loadBenefitsData
    Escenario: Editar y activar un beneficio sin sucursales adheridas
        Dado espero a que aparezca el contenido dinámico "nisi" en "#benefits"
        Y hago click y sigo "#benefits table .action-icon:eq(3)"
        Y espero a que aparezca el contenedor dinámico ".benefit-form"
        Y tildo el checkbox "active"
        Y relleno "owner" con "Marina Sucari"
        Y relleno "name" con "BNF > Todos los lues"
        Y selecciono "10%" de "discount"
        Y selecciono "General" de "targetUserType"
        Y relleno la fecha "validFrom" con "01/12/2013"
        Y marco "expires"
        Y relleno la fecha "validUntil" con "01/12/2014"
        Y hago click en "#ms-redeemingMethods .ms-selectable li:eq(1)"
        Y hago click en "#ms-paymentMethods .ms-selectable li:eq(0)"
        Y hago click en "#ms-paymentMethods .ms-selectable li:eq(2)"
        Y relleno "title" con "10% de descuento en la compra de..."
        Y lleno el WYSIWYG "description" con "En la compra de zapatillas te hacemos un 10%"
        Y agrego tag "zapatillas" en el elemento "#tag-input"
        Y agrego tag "deportes" en el elemento "#tag-input"
        Y agrego tag "correr" en el elemento "#tag-input"
        Y agrego tag "zapatillas para correr" en el elemento "#tag-input"
        Y hago click en "#ms-categories .ms-selectable li:eq(1)"
        Cuando presiono "Guardar"
        Entonces espero a que aparezca el contenido dinámico "Debe tener sucursales adheridas para activar el beneficio" en ".alert-error"

    @javascript @loadBenefitsBenefitData
    Escenario: Editar un nuevo beneficio vacio
        Dado espero a que aparezca el contenido dinámico "culpa" en "#benefits"
        Y hago click y sigo "#benefits .action-icon:eq(0)"
        Y espero a que aparezca el contenedor dinámico ".benefit-form"
        Y relleno "owner" con ""
        Y relleno "name" con ""
        Y relleno la fecha "validFrom" con "01/12/2013"
        Cuando presiono "Guardar"
        Entonces debo ver "Este campo no puede estar vacío"

    @javascript @loadBenefitsBenefitData
    Escenario: Editar beneficio superando los 80 caracteres
        Dado espero a que aparezca el contenido dinámico "culpa" en "#benefits table"
        Y hago click y sigo "#benefits .action-icon:eq(0)"
        Y espero a que aparezca el contenedor dinámico ".benefit-form"
        Y relleno "owner" con "Marina Sucari Marina SucariMarina SucariMarina SucariMarina SucariMarina SucariMarina SucariMarina SucariMarina Sucari"
        Y relleno "name" con "BBNF > Todos los luesBNF > Todos los luesBNF > Todos los luesBNF > Todos los luesBNF > Todos los luesBNF > Todos los luesNF > Todos los lues"
        Y relleno "title" con "110% de descuento en la compra de...10% de descuento en la compra de...10% de descuento en la compra de...10% de descuento en la compra de...10% de descuento en la compra de...10% de descuento en la compra de...10% de descuento en la compra de...10% de descuento en la compra de...0% de descuento en la compra de..."
        Cuando presiono "Guardar"
        Entonces debo ver "El responsable no puede superar los 80 caracteres"
        Y debo ver "El nombre no puede superar los 80 caracteres"
        Y debo ver "El titulo no puede superar los 80 caracteres"
