#language: es
Característica: Como usuario administrador del backoffice quiero crear una sucursal para un comercio

    Antecedentes:
        Dado estoy en "/backoffice/signin" 
        Y relleno "_username" con "apibackofficetester" 
        Y relleno "_password" con "apitesterbackoffice" 
        Y presiono "_submit"
        Y sigo "Beneficios Corporativos"
        Y espero a que aparezca el contenido dinámico "Listado de Comercios" en ".breadcrumb"
        Y espero a que aparezca el contenido dinámico "45 minutos" en ".backgrid-company-list"
        Y relleno "filters[name]" con "Panamericano Bariloche"
        Y hago click en "#name-filter-btn-submit"
        Entonces espero a que aparezca el contenido dinámico "Panamericano Bariloche" en ".backgrid-company-list"
        Cuando sigo "Panamericano Bariloche"
        Y espero a que aparezca el contenedor dinámico ".company-view-container"
        Entonces el breadcrumb debe ser "Beneficios Corporativos > Listado de Comercios > Panamericano Bariloche"
        Y espero a que aparezca el contenido dinámico "Panamericano Bariloche" en ".backoffice-header"
        Y sigo "Sucursales (27)"
        Y espero a que aparezca el contenido dinámico "Balvanera" en "#stores"
        Y hago click y sigo "#stores .complete-list-link"
        Y espero a que aparezca el contenido dinámico "Listar sucursales" en ".breadcrumb"

    @javascript @loadBenefitsData
    Escenario: Crear una nueva sucursal de tipo local
        Y sigo "Nueva sucursal"
        Entonces espero a que aparezca el contenedor dinámico ".store-form .form-horizontal"
        Y selecciono "outlet" de "type"
        Y relleno "name" con "Casa Central"
        Y hago click en "#contact-list"
        Y espero a que aparezca el contenido dinámico "Seleccione un contacto" en ".modal-title"
        Y espero a que aparezca el contenido dinámico "Catalina Carnovale" en ".selected-item"
        Y sigo "Catalina Carnovale"
        Y debo ver "Catalina Carnovale" en el campo ".label-selected"
        Y relleno "phone" con "01123235689"
        Y relleno "companyName" con "Topper S.A"
        Y relleno "taxId" con "234561232"
        Y relleno "zipCode" con "1212"
        Y relleno "webSite" con "http://www.munchis.com.ar"
        Y espero a que aparezca ".txt-search"
        Y relleno "txt-search" con "Alvarez Thomas 198 ciudad autónoma de buenos aires"
        Y hago click en ".search-btn"
        Cuando presiono "Guardar"
        Entonces espero a que aparezca el contenedor dinámico ".store-basic-information"
        Y el breadcrumb debe ser "Inicio > Beneficios Corporativos > Listado de Comercios > Panamericano Bariloche > Sucursales > Casa Central"
        Y la URL debe seguir el patrón "/backoffice/benefits/store/\d+/view"

    @javascript @loadBenefitsData
    Escenario: Crear una nueva sucursal de tipo local sin datos obligatorios
        Y sigo "Nueva sucursal"
        Entonces espero a que aparezca el contenedor dinámico ".store-form .form-horizontal"
        Y selecciono "outlet" de "type"
        Cuando presiono "Guardar"
        Entonces espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-name .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-companyName .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-taxId .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-phone .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-contact .help-block"        
        Y debo ver "Por favor, complete con una ubicación"

    @javascript @loadBenefitsData
    Escenario: Crear una nueva sucursal de tipo online
        Y sigo "Nueva sucursal"
        Entonces espero a que aparezca el contenedor dinámico ".store-form .form-horizontal"
        Y selecciono "online" de "type"
        Y espero a que aparezca el contenido dinámico "Agregar área geográfica" en ".add-new-area"
        Y relleno "name" con "Colegiales"
        Y hago click en "#contact-list"
        Y espero a que aparezca el contenido dinámico "Seleccione un contacto" en ".modal-title"
        Y espero a que aparezca el contenido dinámico "Catalina Carnovale" en ".selected-item"
        Y sigo "Catalina Carnovale"
        Y debo ver "Catalina Carnovale" en el campo ".label-selected"
        Y relleno "phone" con "01123235689"
        Y relleno "companyName" con "Topper S.A"
        Y relleno "taxId" con "234561232"        
        Y relleno "webSite" con "http://www.munchis.com.ar"
        Y relleno "txt-search" con "Palermo, Buenos Aires" y presiono enter
        Y espero a que aparezca el contenido dinámico "Palermo" en ".geographical-area-parents"
        Y espero a que aparezca el contenido dinámico "Buenos Aires" en ".geographical-area-parents"
        Y espero a que aparezca el contenido dinámico "Argentina" en ".geographical-area-parents"
        Y presiono "Agregar área geográfica"
        Y espero a que aparezca el contenido dinámico "Ingrese un área geográfica" en "#accordion"
        Y espero a que aparezca el contenedor dinámico ".collapse.in .txt-search"
        Y completo campo "input[name=\'txt-search\']:eq(1)" con "Recoleta Buenos Aires Argentina"
        Y hago click en ".search-btn"
        Y espero a que aparezca el contenido dinámico "Recoleta" en ".geographical-area-parents"
        Y espero a que aparezca el contenido dinámico "Buenos Aires" en ".geographical-area-parents"
        Y espero a que aparezca el contenido dinámico "Argentina" en ".geographical-area-parents"
        Cuando presiono "Guardar"
        Entonces espero a que aparezca el contenedor dinámico ".store-basic-information"
        Y el breadcrumb debe ser "Inicio > Beneficios Corporativos > Listado de Comercios > Panamericano Bariloche > Sucursales > Colegiales"
        Y la URL debe seguir el patrón "/backoffice/benefits/store/\d+/view"

    @javascript @loadBenefitsData
    Escenario: Crear una nueva sucursal de tipo online sin datos obligatorios
        Y sigo "Nueva sucursal"
        Entonces espero a que aparezca el contenedor dinámico ".store-form .form-horizontal"
        Y selecciono "online" de "type"
        Cuando presiono "Guardar"
        Entonces espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-name .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-companyName .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-taxId .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-phone .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-contact .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-webSite .help-block"
        Y debo ver "Por favor, complete con una ubicación"

    @javascript @loadBenefitsData
    Escenario: Crear una nueva sucursal de tipo telefónica
        Y sigo "Nueva sucursal"
        Entonces espero a que aparezca el contenedor dinámico ".store-form .form-horizontal"
        Y selecciono "phone" de "type"
        Y relleno "name" con "Centro"
        Y hago click en "#contact-list"
        Y espero a que aparezca el contenido dinámico "Seleccione un contacto" en ".modal-title"
        Y espero a que aparezca el contenido dinámico "Catalina Carnovale" en ".selected-item"
        Y sigo "Catalina Carnovale"
        Y debo ver "Catalina Carnovale" en el campo ".label-selected"
        Y relleno "phone" con "01123235689"
        Y relleno "companyName" con "Topper S.A"
        Y relleno "taxId" con "234561232"        
        Y relleno "webSite" con "http://www.munchis.com.ar"
        Y relleno "txt-search" con "Palermo, Buenos Aires"
        Y hago click en ".search-btn"
        Y espero a que aparezca el contenido dinámico "Palermo" en ".geographical-area-parents"
        Y espero a que aparezca el contenido dinámico "Buenos Aires" en ".geographical-area-parents"
        Y espero a que aparezca el contenido dinámico "Argentina" en ".geographical-area-parents"
        Y presiono "Agregar área geográfica"
        Y espero a que aparezca el contenido dinámico "Ingrese un área geográfica" en "#accordion"
        Y espero a que aparezca el contenedor dinámico ".collapse.in .txt-search"
        Y completo campo "input[name=\'txt-search\']:eq(1)" con "Recoleta Buenos Aires Argentina"
        Y hago click en ".search-btn"
        Y espero a que aparezca el contenido dinámico "Recoleta" en ".geographical-area-parents"
        Y espero a que aparezca el contenido dinámico "Buenos Aires" en ".geographical-area-parents"
        Y espero a que aparezca el contenido dinámico "Argentina" en ".geographical-area-parents"
        Cuando presiono "Guardar"
        Entonces espero a que aparezca el contenedor dinámico ".store-basic-information"
        Y el breadcrumb debe ser "Inicio > Beneficios Corporativos > Listado de Comercios > Panamericano Bariloche > Sucursales > Centro"
        Y la URL debe seguir el patrón "/backoffice/benefits/store/\d+/view"

    @javascript @loadBenefitsData
    Escenario: Crear una nueva sucursal de tipo telefónica sin datos obligatorios
        Y sigo "Nueva sucursal"
        Entonces espero a que aparezca el contenedor dinámico ".store-form .form-horizontal"
        Y selecciono "phone" de "type"
        Cuando presiono "Guardar"
        Entonces espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-name .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-companyName .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-taxId .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-phone .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-contact .help-block"
        Y debo ver "Por favor, complete con una ubicación"

    @javascript @loadBenefitsData
    Escenario: Crear una sucusal sin respetar el máximo de caracteres en los campos
        Y sigo "Nueva sucursal"
        Entonces espero a que aparezca el contenedor dinámico ".store-form .form-horizontal"
        Y selecciono "outlet" de "type"
        Y relleno "name" con "CasaCentralCasaCentralCasaCentralCasaCentralCasaCentralCasaCentralCasaCentralCasaCentral"
        Y hago click en "#contact-list"
        Y espero a que aparezca el contenido dinámico "Seleccione un contacto" en ".modal-title"
        Y espero a que aparezca el contenido dinámico "Catalina Carnovale" en ".selected-item"
        Y sigo "Catalina Carnovale"
        Y debo ver "Catalina Carnovale" en el campo ".label-selected"
        Y relleno "phone" con "01123235689"
        Y relleno "companyName" con "MunchisSAMunchisSAMunchisSAMunchisSAMunchisSAMunchisSAMunchisSAMunchisSAMunchisSAMunchisSA"
        Y relleno "taxId" con "234561232"        
        Y relleno "zipCode" con "1212"
        Y relleno "webSite" con "http://www.munchis.com.ar"
        Y relleno "txt-search" con "Alvarez Thomas 198 ciudad autónoma de buenos aires"
        Y hago click en ".search-btn"
        Cuando presiono "Guardar"
        Entonces debo ver "El nombre de la sucursal no puede superar los 80 caracteres"
        Y debo ver "La razón social de la sucursal no puede superar los 80 caracteres"