#language: es
Característica: Como usuario administrador del backoffice quiero crear una sucursal para un comercio

    Antecedentes:
        Dado estoy en "/backoffice/signin" 
        Y relleno "_username" con "apibackofficetester" 
        Y relleno "_password" con "apitesterbackoffice" 
        Y presiono "_submit"
        Y sigo "Beneficios Corporativos"
        Y espero a que aparezca el contenido dinámico "Listado de Comercios" en ".breadcrumb"
        Y espero a que aparezca el contenido dinámico "45 minutos" en ".backgrid-company-list"
        Y relleno "filters[name]" con "Regalos al Mundo"
        Y hago click en "#name-filter-btn-submit"
        Entonces espero a que aparezca el contenido dinámico "Regalos al Mundo" en ".backgrid-company-list"
        Cuando sigo "Regalos al Mundo"
        Y espero a que aparezca el contenedor dinámico ".company-view-container"
        Entonces el breadcrumb debe ser "Beneficios Corporativos > Listado de Comercios > Regalos al Mundo"
        Y espero a que aparezca el contenido dinámico "Regalos al Mundo" en ".backoffice-header"
        Y sigo "Sucursales (2)"
        Y espero a que aparezca el contenido dinámico "Eulogio Estigarribia" en "#stores"

    @javascript @loadBenefitsData
    Escenario: Editar sucursal de tipo local
        Dado hago click y sigo "#stores .action-icon:first"
        Entonces espero a que aparezca el contenido dinámico "Editar sucursal" en ".breadcrumb"
        Y espero a que aparezca el contenedor dinámico ".store-form .form-horizontal"
        Y relleno "name" con "Casa Central"
        Y hago click en ".overlay-label .btn-close"
        Y hago click en "#contact-list"
        Y espero a que aparezca el contenido dinámico "Seleccione un contacto" en ".modal-title"
        Y espero a que aparezca el contenido dinámico "Daniela Musalem" en ".selected-item"
        Y sigo "Daniela Musalem"
        Y debo ver "Daniela Musalem" en el campo ".label-selected"
        Y presiono "Cambiar ubicación"
        Y relleno "txt-search" con "Alvarez Thomas 198 ciudad autónoma de buenos aires"
        Y hago click en ".search-btn"
        Y relleno "phone" con "01123235689"
        Y relleno "companyName" con "Topper S.A"
        Y relleno "zipCode" con "1212"
        Y relleno "taxId" con "234561232"        
        Y relleno "webSite" con "http://www.munchis.com.ar"
        Cuando presiono "Guardar"
        Entonces espero a que aparezca el contenedor dinámico ".store-basic-information"
        Y el breadcrumb debe ser "Inicio > Beneficios Corporativos > Listado de Comercios > Regalos al Mundo > Sucursales > Casa Central"
        Y la URL debe seguir el patrón "/backoffice/benefits/store/\d+/view"

    @javascript @loadBenefitsData
    Escenario:Editar una sucursal de tipo local sin datos obligatorios
        Dado hago click y sigo "#stores .action-icon:first"
        Entonces espero a que aparezca el contenido dinámico "Editar sucursal" en ".breadcrumb"
        Y espero a que aparezca el contenedor dinámico ".store-form .form-horizontal"
        Y relleno "name" con " "
        Y hago click en ".overlay-label .btn-close"
        Y relleno "companyName" con " "
        Y relleno "taxId" con " "
        Y relleno "phone" con " "        
        Cuando presiono "Guardar"
        Entonces espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-name .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-companyName .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-taxId .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-phone .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-contact .help-block"

    @javascript @loadBenefitsData
    Escenario: Editar una sucursal de tipo online
        Dado hago click y sigo "#stores .action-icon:eq(1)"
        Entonces espero a que aparezca el contenido dinámico "Editar sucursal" en ".breadcrumb"
        Y espero a que aparezca el contenido dinámico "Puerto Madero, CABA, Argentina" en "#accordion"
        Y espero a que aparezca el contenido dinámico "Recoleta, CABA, Argentina" en "#accordion"
        Y relleno "name" con "Colegiales"
        Y hago click en ".overlay-label .btn-close"
        Y hago click en "#contact-list"
        Y espero a que aparezca el contenido dinámico "Seleccione un contacto" en ".modal-title"
        Y espero a que aparezca el contenido dinámico "Daniela Musalem" en ".selected-item"
        Y sigo "Daniela Musalem"
        Y debo ver "Daniela Musalem" en el campo ".label-selected"
        Y relleno "phone" con "01123235689"
        Y relleno "companyName" con "Topper S.A"
        Y relleno "taxId" con "234561232"
        Y relleno "webSite" con "http://www.munchis.com.ar"
        Y presiono "Agregar área geográfica"
        Y espero a que aparezca el contenido dinámico "Ingrese un área geográfica" en "#accordion"
        Y espero a que aparezca el contenedor dinámico ".collapse.in .txt-search"
        Y completo campo "input[name=\'txt-search\']:eq(2)" con "Recoleta Buenos Aires Argentina"
        Y hago click en ".search-btn"
        Y espero a que aparezca el contenido dinámico "Recoleta, CABA, Argentina" en "#accordion"
        Cuando presiono "Guardar"
        Entonces espero a que aparezca el contenedor dinámico ".store-basic-information"
        Y el breadcrumb debe ser "Inicio > Beneficios Corporativos > Listado de Comercios > Regalos al Mundo > Sucursales > Colegiales"
        Y la URL debe seguir el patrón "/backoffice/benefits/store/\d+/view"

    @javascript @loadBenefitsData
    Escenario: Edito una sucursal de tipo online sin datos obligatorios
        Dado hago click y sigo "#stores .action-icon:eq(1)"
        Entonces espero a que aparezca el contenido dinámico "Editar sucursal" en ".breadcrumb"
        Y espero a que aparezca el contenedor dinámico ".store-form .form-horizontal"
        Y relleno "name" con " "
        Y hago click en ".overlay-label .btn-close"
        Y relleno "companyName" con ""
        Y relleno "taxId" con " "
        Y relleno "phone" con " "        
        Y relleno "webSite" con " "
        Cuando presiono "Guardar"
        Entonces espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-name .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-companyName .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-taxId .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-phone .help-block"
        Y espero a que aparezca el contenido dinámico "Este campo no puede estar vacío" en ".form-contact .help-block"        
        Y espero a que aparezca el contenido dinámico "Ingrese una URL válida" en ".form-webSite .help-block"

    @javascript @loadBenefitsData
    Escenario: Crear una sucusal sin respetar el máximo de caracteres en los campos
        Dado hago click y sigo "#stores .action-icon:eq(1)"
        Entonces espero a que aparezca el contenido dinámico "Editar sucursal" en ".breadcrumb"
        Y espero a que aparezca el contenedor dinámico ".store-form .form-horizontal"
        Y espero a que aparezca el contenido dinámico "Puerto Madero, CABA, Argentina" en "#accordion"
        Y espero a que aparezca el contenido dinámico "Recoleta, CABA, Argentina" en "#accordion"
        Y relleno "name" con "CasaCentralCasaCentralCasaCentralCasaCentralCasaCentralCasaCentralCasaCentralCasaCentral"
        Y relleno "companyName" con "MunchisSAMunchisSAMunchisSAMunchisSAMunchisSAMunchisSAMunchisSAMunchisSAMunchisSAMunchisSA"
        Cuando presiono "Guardar"
        Entonces debo ver "El nombre de la sucursal no puede superar los 80 caracteres"
        Y debo ver "La razón social de la sucursal no puede superar los 80 caracteres"
