#language: es
Característica: Crear un usuario en la plataforma desde el backoffice.

    Antecedentes:
        Dado estoy en "/backoffice/signin"
        Y relleno "_username" con "apibackofficetester"
        Y relleno "_password" con "apitesterbackoffice"
        Y presiono "_submit"
        Cuando sigo "Listar Cuentas"
        Entonces debe aparecer el contenido dinámico "GoIntegro Argentina" en ".string-cell"
        Y hago click en ".dropdown-toggle"
        Y sigo "Listar plataformas de GoIntegro Argentina"

    @javascript @createPlatformAndAccountAndOneUser
    Escenario: Crear un usuario en la plataforma desde el backoffice
        Dado espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
        Y sigo "GoIntegro Platform CI"
        Y espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".breadcrumb"
        Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
        Y hago click en ".more-options"
        Y sigo "Usuarios"
        Y espero a que aparezca el contenido dinámico "Nuevo usuario" en ".block-company-list"
        Y sigo "Nuevo usuario"
        Y espero a que aparezca el contenido dinámico "Información básica" en ".backoffice-block"
        Y relleno "name" con "Usuario"
        Y relleno "surname" con "GoIntegro"
        Y relleno "email" con "usuario.test@gointegro.com"
        Y relleno "document" con "87456123"
        Y selecciono "27" de "birthdate-day"
        Y selecciono "Febrero" de "birthdate-month"
        Y selecciono "1986" de "birthdate-year"
        Y relleno "gender" con "Masculino"
        Y relleno "phone" con "11111111"
        Y relleno "cellphone" con "11111111"
        Y relleno "usernameId" con "GoIntegro"
        Y marco "registered"
        Y relleno la fecha "registeredDate" con "07/05/2013"
        Y marco "enabled"
        Y relleno "position" con "Vicepresidente Jr."
        #jefe
        Y hago click en ".form-chief .overlay-list"
        Y espero a que aparezca el contenedor dinámico ".modal-body"
        Y espero a que aparezca el contenido dinámico "Tyrion Lannister" en ".modal-body"
        Y hago click en ".modal-body .selected-item:eq(0)"
        Cuando presiono "Guardar"
        Y espero a que cambie la URL
        Entonces la URL debe seguir el patrón "/backoffice/user/\d+/view"
        Y debo ver "Usuario"
        Y debo ver "GoIntegro"
        Y debo ver "usuario.test@gointegro.com"

    @javascript @createPlatformAndAccountAndOneUser
    Escenario: Crear un usuario en la plataforma desde el backoffice con un mail existente
        Dado espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
        Y sigo "GoIntegro Platform CI"
        Y espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".breadcrumb"
        Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
        Y hago click en ".more-options"
        Y sigo "Usuarios"
        Y espero a que aparezca el contenido dinámico "Nuevo usuario" en ".block-company-list"
        Y sigo "Nuevo usuario"
        Y espero a que aparezca el contenido dinámico "Información básica" en ".backoffice-block"
        Y relleno "name" con "Usuario"
        Y relleno "surname" con "GoIntegro"
        Y relleno "email" con "tyrion.lannister@gointegro.com"
        Y relleno "document" con "87456123"
        Y selecciono "30" de "birthdate-day"
        Y selecciono "Octubre" de "birthdate-month"
        Y selecciono "1986" de "birthdate-year"
        Y relleno "gender" con "Femenino"
        Y relleno "phone" con "11111111"
        Y relleno "cellphone" con "11111111"
        Y relleno "usernameId" con "GoIntegro"
        Y marco "registered"
        Y relleno la fecha "registeredDate" con "07/05/2013"
        Y marco "enabled"
        Cuando presiono "Guardar"
        Entonces debe aparecer el contenido dinámico "El usuario ya existe" en ".alert-error"

    @javascript @createPlatformAndAccountAndOneUser
    Escenario: Crear un usuario en la plataforma desde el backoffice con id de usuario existente
        Dado espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
        Y sigo "GoIntegro Platform CI"
        Y espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".breadcrumb"
        Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
        Y hago click en ".more-options"
        Y sigo "Usuarios"
        Y espero a que aparezca el contenido dinámico "Nuevo usuario" en ".block-company-list"
        Y sigo "Nuevo usuario"
        Y espero a que aparezca el contenido dinámico "Información básica" en ".backoffice-block"
        Y relleno "name" con "Usuario"
        Y relleno "surname" con "Behat"
        Y relleno "email" con "usuario.behat@gointegro.com"
        Y relleno "document" con "45454545"
        Y selecciono "15" de "birthdate-day"
        Y selecciono "Agosto" de "birthdate-month"
        Y selecciono "1979" de "birthdate-year"
        Y relleno "gender" con "Masculino"
        Y relleno "phone" con "11111111"
        Y relleno "cellphone" con "11111111"
        Y relleno "usernameId" con "tyrion"
        Y marco "registered"
        Y relleno la fecha "registeredDate" con "07/05/2013"
        Y marco "enabled"
        Cuando presiono "Guardar"
        Entonces debe aparecer el contenido dinámico "El usuario ya existe" en ".alert-error"

    @javascript @createPlatformAndAccountAndOneUser
    Escenario: Crear un usuario en la plataforma desde el backoffice dejando todos los campos vacíos
        Dado espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
       Y sigo "GoIntegro Platform CI"
        Y espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".breadcrumb"
        Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
        Y hago click en ".more-options"
        Y sigo "Usuarios"
        Y espero a que aparezca el contenido dinámico "Nuevo usuario" en ".block-company-list"
        Y sigo "Nuevo usuario"
        Y espero a que aparezca el contenido dinámico "Información básica" en ".backoffice-block"
        Cuando presiono "Guardar"
        Y debo ver "Este campo no puede estar vacío"

    @javascript @createPlatformAndAccountAndOneUser
    Escenario: Crear un usuario en la plataforma desde el backoffice con Email inválido
        Dado espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
        Y sigo "GoIntegro Platform CI"
        Y espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".breadcrumb"
        Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
        Y hago click en ".more-options"
        Y sigo "Usuarios"
        Y espero a que aparezca el contenido dinámico "Nuevo usuario" en ".block-company-list"
        Y sigo "Nuevo usuario"
        Y espero a que aparezca el contenido dinámico "Información básica" en ".backoffice-block"
        Y relleno "name" con "Usuario"
        Y relleno "surname" con "Test"
        Y relleno "email" con "testing email"
        Y selecciono "27" de "birthdate-day"
        Y selecciono "Febrero" de "birthdate-month"
        Y selecciono "1987" de "birthdate-year"
        Y relleno "usernameId" con "testing"
        Y marco "enabled"
        Cuando presiono "Guardar"
        Entonces debo ver "Por favor ingrese un mail válido"

    @javascript @createPlatformAndAccountAndOneUser
    Escenario: Crear un usuario con nombre inválido y fecha de registro futura
        Dado espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
        Y sigo "GoIntegro Platform CI"
        Y espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".breadcrumb"
        Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
        Y hago click en ".more-options"
        Y sigo "Usuarios"
        Y espero a que aparezca el contenido dinámico "Nuevo usuario" en ".block-company-list"
        Y sigo "Nuevo usuario"
        Y espero a que aparezca el contenido dinámico "Información básica" en ".backoffice-block"
        Y relleno "name" con "++User%test"
        Y relleno "surname" con "s!!**--6893"
        Y relleno "document" con "/*/*/---*/"
        Y relleno la fecha "registeredDate" con "27/03/2050"
        Cuando presiono "Guardar"
        Entonces espero a que aparezca el contenido dinámico "Por favor ingrese un nombre válido" en ".form-name"
        Y espero a que aparezca el contenido dinámico "Por favor ingrese un apellido válido" en ".form-surname"
        Y espero a que aparezca el contenido dinámico "Ingresar sólo números y/o letras. Máximo 20 caracteres" en ".form-document"
        Y espero a que aparezca el contenido dinámico "La fecha ingresada no puede ser mayor a la fecha actual" en ".form-registeredDate"

    @javascript @createPlatformAndAccountAndOneUser
    Escenario: Crear un usuario para una plataforma con unique field DOCUMENT
        Dado espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
        Y sigo "GoIntegro Platform CI"
        Y espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".breadcrumb"
        Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
        Y hago click en ".more-options"
        Y sigo "Usuarios"
        Y espero a que aparezca el contenido dinámico "Nuevo usuario" en ".block-company-list"
        Y sigo "Nuevo usuario"
        Y espero a que aparezca el contenido dinámico "Información básica" en ".backoffice-block"
        Y marco "registered"
        Y relleno "email" con "usuario.test@gointegro.com"
        Cuando presiono "Guardar"
        Entonces debo ver "El documento no puede ser vacío porque es el campo único de la plataforma"

    @javascript @createPlatformAndAccountAndOneUser
    Escenario: Crear un usuario con documento vacío y marcándolo como registrado.
        Dado espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
        Y sigo "GoIntegro Platform CI"
        Y espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".breadcrumb"
        Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
        Y hago click en ".more-options"
        Y sigo "Usuarios"
        Y espero a que aparezca el contenido dinámico "Nuevo usuario" en ".block-company-list"
        Y sigo "Nuevo usuario"
        Y espero a que aparezca el contenido dinámico "Información básica" en ".backoffice-block"
        Y marco "registered"
        Cuando presiono "Guardar"
        Entonces debo ver "Un usuario registrado no puede tener el email vacío"