#language: es
Característica: Crear ambiente de una plataforma como usuario administrador desde el backoffice.

  Antecedentes:
    Dado estoy en "/backoffice/signin"
    Y relleno "_username" con "apibackofficetester"
    Y relleno "_password" con "apitesterbackoffice"
    Cuando presiono "_submit"
    Entonces estoy en "/backoffice/"

  @javascript @createPlatformAndAccountAndOneUser
  Escenario: Crear un ambiente asociado a una plataforma desde el backoffice con los campos requeridos viendo el detalle del ambiente creado
    Dado estoy en "/backoffice/"
    Y sigo "ListAccounts"
    Y debe aparecer el contenido dinámico "GoIntegro Argentina" en ".string-cell"
    Y hago click en ".dropdown-toggle"
    Y sigo "btnListPlatformsFor"
    Y debe aparecer el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
    Y sigo "GoIntegro Platform CI"
    Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
    Y hago click en ".more-options"
    Y sigo "Ambientes"
    Y sigo "Nuevo ambiente"
    Y espero a que aparezca el contenido dinámico "Nombre" en ".field-name"
    Y relleno "name" con "Recursos Humanos"
    Y debo ver "GoIntegro Platform CI"
    Y selecciono "Plataforma" de "service"
    Cuando presiono "btnSave"
    Y espero a que cambie la URL
    Entonces debo ver "Recursos Humanos"
    Y debo ver "GoIntegro Platform CI"
    Y debo ver "Plataforma"

  @javascript @createPlatformAndAccountAndOneUser
  Escenario: Crear un ambiente asociado a una plataforma desde el backoffice con acceso público sin login
    Dado estoy en "/backoffice/"
    Y sigo "ListAccounts"
    Y debe aparecer el contenido dinámico "GoIntegro Argentina" en ".string-cell"
    Y hago click en ".dropdown-toggle"
    Y sigo "btnListPlatformsFor"
    Y debe aparecer el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
    Y sigo "GoIntegro Platform CI"
    Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
    Y hago click en ".more-options"
    Y sigo "Ambientes"
    Y sigo "Nuevo ambiente"
    Y espero a que aparezca el contenido dinámico "Nombre" en ".field-name"
    Y relleno "name" con "Recursos Humanos"
    Y debo ver "GoIntegro Platform CI"
    Y selecciono "Plataforma" de "service"
    Y selecciono "Grilla + Muro" de "homeLayout"
    Y selecciono "Público sin Login" de "accessType"
    Y debe estar seleccionado "fullGrid" en "homeLayout"
    Y el campo "homeLayout" debe estar deshabilitado
    Cuando presiono "btnSave"
    Y espero a que cambie la URL
    Entonces debo ver "Recursos Humanos"
    Y debo ver "GoIntegro Platform CI"
    Y debo ver "Plataforma"

  @javascript @createPlatformAndAccountAndOneUser
  Escenario: Crear un ambiente asociado a una plataforma desde el backoffice con los campos requeridos y volver al formulario para crear otro ambiente
    Dado estoy en "/backoffice/"
    Y sigo "ListAccounts"
    Y debe aparecer el contenido dinámico "GoIntegro Argentina" en ".string-cell"
    Y hago click en ".dropdown-toggle"
    Y sigo "btnListPlatformsFor"
    Y debe aparecer el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
    Y sigo "GoIntegro Platform CI"
    Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
    Y hago click en ".more-options"
    Y sigo "Ambientes"
    Y sigo "Nuevo ambiente"
    Y espero a que aparezca el contenido dinámico "Nombre" en ".field-name"
    Y relleno "name" con "Beneficios Corporativos"
    Y debo ver "GoIntegro Platform CI"
    Y selecciono "Plataforma" de "service"
    Cuando presiono "btnSaveNew"
    Entonces espero a que aparezca el contenido dinámico "El ambiente se creó correctamente" en "#content"
    Y el campo "name" debe estar vacio

  @javascript @createPlatformAndAccountAndOneUser
  Escenario: Crear un ambiente asociado a una plataforma desde el backoffice con nombre de ambiente existente
    Dado estoy en "/backoffice/"
    Y sigo "ListAccounts"
    Y debe aparecer el contenido dinámico "GoIntegro Argentina" en ".string-cell"
    Y hago click en ".dropdown-toggle"
    Y sigo "btnListPlatformsFor"
    Y debe aparecer el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
    Y sigo "GoIntegro Platform CI"
    Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
    Y hago click en ".more-options"
    Y sigo "Ambientes"
    Y sigo "Nuevo ambiente"
    Y espero a que aparezca el contenido dinámico "Nombre" en ".field-name"
    Y relleno "name" con "iConnection"
    Y debo ver "GoIntegro Platform CI"
    Y selecciono "Beneficios" de "service"
    Y relleno "subdomain" con "sitiodeprueba"
    Cuando presiono "btnSave"
    Entonces debe aparecer el contenido dinámico "El nombre de ambiente ya existe para esta plataforma." en "#content"

  @javascript @createPlatformAndAccountAndOneUser
  Escenario: Crear un ambiente asociado a una plataforma desde el backoffice con nombre de ambiente inválido
    Dado estoy en "/backoffice/"
    Y sigo "ListAccounts"
    Y debe aparecer el contenido dinámico "GoIntegro Argentina" en ".string-cell"
    Y hago click en ".dropdown-toggle"
    Y sigo "btnListPlatformsFor"
    Y debe aparecer el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
    Y sigo "GoIntegro Platform CI"
    Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
    Y hago click en ".more-options"
    Y sigo "Ambientes"
    Y sigo "Nuevo ambiente"
    Y espero a que aparezca el contenido dinámico "Nombre" en ".field-name"
    Y relleno "name" con " "
    Y debo ver "GoIntegro Platform CI"
    Y selecciono "Beneficios" de "service"
    Y relleno "subdomain" con "sitiodeprueba"
    Cuando presiono "btnSave"
    Entonces debe aparecer el contenido dinámico "Campo obligatorio." en "#content"

  @javascript @createPlatformAndAccountAndOneUser
  Escenario: Crear un ambiente asociado a una plataforma desde el backoffice con servicio de reconocimientos y un subdominio vacío
    Dado estoy en "/backoffice/"
    Y sigo "ListAccounts"
    Y debe aparecer el contenido dinámico "GoIntegro Argentina" en ".string-cell"
    Y hago click en ".dropdown-toggle"
    Y sigo "btnListPlatformsFor"
    Y debe aparecer el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
    Y sigo "GoIntegro Platform CI"
    Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
    Y hago click en ".more-options"
    Y sigo "Ambientes"
    Y sigo "Nuevo ambiente"
    Y espero a que aparezca el contenido dinámico "Nombre" en ".field-name"
    Entonces relleno "name" con "iRecognition"
    Y debo ver "GoIntegro Platform CI"
    Y selecciono "Reconocimientos" de "service"
    Cuando presiono "btnSave"
    Entonces debe aparecer el contenido dinámico "El campo url no puede ser vacío." en "#content"

  @javascript @createPlatformAndAccountAndOneUser
  Escenario: Crear un ambiente asociado a una plataforma desde el backoffice con servicio de reconocimientos y un subdominio inválido
    Dado estoy en "/backoffice/"
    Y sigo "ListAccounts"
    Y debe aparecer el contenido dinámico "GoIntegro Argentina" en ".string-cell"
    Y hago click en ".dropdown-toggle"
    Y sigo "btnListPlatformsFor"
    Y debe aparecer el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
    Y sigo "GoIntegro Platform CI"
    Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
    Y hago click en ".more-options"
    Y sigo "Ambientes"
    Y sigo "Nuevo ambiente"
    Y espero a que aparezca el contenido dinámico "Nombre" en ".field-name"
    Entonces relleno "name" con "iRecognition"
    Y debo ver "GoIntegro Platform CI"
    Y selecciono "Reconocimientos" de "service"
    Y relleno "subdomain" con "http://irecognition"
    Cuando presiono "btnSave"
    Entonces debe aparecer el contenido dinámico "El campo url no puede contener 'http://' ni 'https://'." en "#content"

  @javascript @createAccountAndUserAndPlatformAndEnvironment
  Escenario: Creación de un Ambiente con la inhibición visual del mismo en el menú principal de la aplicación.
    Dado estoy en "/backoffice/"
    Y sigo "ListAccounts"
    Y debe aparecer el contenido dinámico "GoIntegro Argentina" en ".string-cell"
    Y hago click en ".dropdown-toggle"
    Y sigo "btnListPlatformsFor"
    Y debe aparecer el contenido dinámico "Plataforma Test" en ".string-cell"
    Y sigo "Plataforma Test"
    Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
    Y hago click en ".more-options"
    Y sigo "Ambientes"
    Y sigo "Nuevo ambiente"
    Y espero a que aparezca el contenido dinámico "Nombre" en ".field-name"
    Y relleno "name" con "Ambiente inhibido"
    Y debo ver "Plataforma Test"
    Y selecciono "Plataforma" de "service"
    Y la casilla de selección "hideEnvironment" debe estar marcada
    Y presiono "Guardar"
    Y espero a que aparezca el contenido dinámico "El ambiente se creó correctamente" en "#content"
    Y sigo "Cerrar Sesión"
    Y estoy en "/auth/signin?_lang=es"
    Y relleno "_username" con "johnconnor"
    Y relleno "_password" con "123456"
    Cuando presiono "_submit"
    Entonces debo estar en "/"
    Y no debo ver "Ambiente inhibido"

  @javascript @createPlatformAndAccountAndOneUser
  Escenario: Crear un ambiente asociado a una plataforma desde el backoffice dejando todos los campos vacíos
    Dado estoy en "/backoffice/"
    Y sigo "ListAccounts"
    Y debe aparecer el contenido dinámico "GoIntegro Argentina" en ".string-cell"
    Y hago click en ".dropdown-toggle"
    Y sigo "btnListPlatformsFor"
    Y debe aparecer el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
    Y sigo "GoIntegro Platform CI"
    Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
    Y hago click en ".more-options"
    Y sigo "Ambientes"
    Y sigo "Nuevo ambiente"
    Y espero a que aparezca el contenido dinámico "Nombre" en ".field-name"
    Y presiono "btnSave"
    Entonces debo ver "Campo obligatorio."
  @javascript @createPlatformAndAccountAndOneUser
  Escenario: Cancelar la creación de un ambiente
    Dado estoy en "/backoffice/"
    Y sigo "ListAccounts"
    Y debe aparecer el contenido dinámico "GoIntegro Argentina" en ".string-cell"
    Y hago click en ".dropdown-toggle"
    Y sigo "btnListPlatformsFor"
    Y debe aparecer el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
    Y sigo "GoIntegro Platform CI"
    Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
    Y hago click en ".more-options"
    Y sigo "Ambientes"
    Y sigo "Nuevo ambiente"
    Y espero a que aparezca el contenido dinámico "Nombre" en ".field-name"
    Cuando presiono "Cancelar"
    Entonces la URL debe seguir el patrón "/backoffice/platform/\d+/environment/list"

  @javascript @createPlatformAndAccountAndOneUser
  Escenario: Crear un ambiente asociado a una plataforma desde el backoffice con caracteres especiales
    Dado estoy en "/backoffice/"
    Y sigo "ListAccounts"
    Y debe aparecer el contenido dinámico "GoIntegro Argentina" en ".string-cell"
    Y hago click en ".dropdown-toggle"
    Y sigo "btnListPlatformsFor"
    Y debe aparecer el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
    Y sigo "GoIntegro Platform CI"
    Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
    Y hago click en ".more-options"
    Y sigo "Ambientes"
    Y sigo "Nuevo ambiente"
    Y espero a que aparezca el contenido dinámico "Nombre" en ".field-name"
    Y relleno "name" con "àÀáÁãÃâÂçÇéÉêÊÍíóÓõÕúÚüÜÑñ"
    Y debo ver "GoIntegro Platform CI"
    Y selecciono "Plataforma" de "service"
    Cuando presiono "btnSaveNew"
    Entonces espero a que aparezca el contenido dinámico "El ambiente se creó correctamente" en "#content"
    Y el campo "name" debe estar vacio