#language: es
Característica: Como usuario del backoffice, ingresar al listado de usuarios y poder Editar un usuario de la plataforma previamente creado.

    Antecedentes:
        Dado estoy en "/backoffice/signin"
        Y relleno "_username" con "apibackofficetester"
        Y relleno "_password" con "apitesterbackoffice"
        Y presiono "_submit"
        Y estoy en "/backoffice/"
        Y sigo "ListAccounts"
        Y debe aparecer el contenido dinámico "GoIntegro Argentina" en ".string-cell"
        Y hago click en ".dropdown-toggle"
        Y sigo "Listar plataformas de GoIntegro Argentina"

    @javascript @createPlatformAndAccountAndOneUser
    Escenario: Editar un usuario
        Dado espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
        Y sigo "GoIntegro Platform CI"
        Y espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".breadcrumb"
        Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
        Y hago click en ".more-options"
        Y sigo "Usuarios"
        Y espero a que aparezca el contenido dinámico "Listado de Usuarios" en ".backoffice-block"
        Y espero a que aparezca el contenido dinámico "Tyrion Lannister" en ".backgrid-user-list"
        Y hago click y sigo ".action-icon:first"
        Y espero a que aparezca el contenido dinámico "Editar usuario" en ".breadcrumb"
        Y espero a que aparezca el contenedor dinámico ".user-form .form-horizontal"
        Y marco "enabled"
        Y relleno "name" con "UsuarioEditado"
        Y relleno "surname" con "TestEditado"
        Y relleno "email" con "usuario.test.editado@gointegro.com"
        Y relleno "document" con "12345678"
        Y selecciono "10" de "birthdate-day"
        Y selecciono "Octubre" de "birthdate-month"
        Y selecciono "1984" de "birthdate-year"
        Y relleno "gender" con "Femenino"
        Y relleno "phone" con "22222222"
        Y relleno "cellphone" con "2222222"
        Y relleno "usernameId" con "testEditado"
        Y relleno la fecha "registeredDate" con "10/10/1984"
        Y selecciono "ROLE_BASIC" de "role"
        Y relleno "position" con "Vicepresidente Jr."
        #jefe
        Y hago click en ".form-chief .overlay-list"
        Y espero a que aparezca el contenedor dinámico ".modal-body"
        Y espero a que aparezca el contenido dinámico "User test" en ".modal-body"
        Y hago click en ".modal-body .selected-item:eq(0)"
        Cuando presiono "Guardar"
        Y espero a que cambie la URL
        Entonces la URL debe seguir el patrón "/backoffice/user/\d+/view"
        Y debo ver "UsuarioEditado"
        Y debo ver "TestEditado"
        Y debo ver "usuario.test.editado@gointegro.com"
        Y debo ver "ROLE_BASIC"

    @javascript @createPlatformAndAccountAndOneUser
    Escenario: Editar un usuario con mail duplicado
        Dado espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
        Y sigo "GoIntegro Platform CI"
        Y espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".breadcrumb"
        Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
        Y hago click en ".more-options"
        Y sigo "Usuarios"
        Y espero a que aparezca el contenido dinámico "Listado de Usuarios" en ".backoffice-block"
        Y espero a que aparezca el contenido dinámico "Tyrion Lannister" en ".backgrid-user-list"
        Y hago click y sigo ".action-icon:first"
        Y espero a que aparezca el contenido dinámico "Editar usuario" en ".breadcrumb"
        Y espero a que aparezca el contenedor dinámico ".user-form .form-horizontal"
        Y relleno "name" con "UsuarioEditado"
        Y relleno "surname" con "TestEditado"
        Y relleno "email" con "test@gointegro.com"
        Y relleno "document" con "123456"
        Y selecciono "20" de "birthdate-day"
        Y selecciono "Diciembre" de "birthdate-month"
        Y selecciono "1998" de "birthdate-year"
        Y relleno "gender" con "Femenino"
        Cuando presiono "Guardar"
        Entonces debe aparecer el contenido dinámico "El usuario ya existe" en ".alert-error"

    @javascript @createPlatformAndAccountAndOneUser
    Escenario: Editar un usuario con mail inválido
        Dado espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
        Y sigo "GoIntegro Platform CI"
        Y espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".breadcrumb"
        Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
        Y hago click en ".more-options"
        Y sigo "Usuarios"
        Y espero a que aparezca el contenido dinámico "Listado de Usuarios" en ".backoffice-block"
        Y espero a que aparezca el contenido dinámico "Tyrion Lannister" en ".backgrid-user-list"
        Y hago click y sigo ".action-icon:first"
        Y espero a que aparezca el contenido dinámico "Editar usuario" en ".breadcrumb"
        Y espero a que aparezca el contenedor dinámico ".user-form .form-horizontal"
        Y relleno "name" con "UsuarioEditado"
        Y relleno "surname" con "TestEditado"
        Y relleno "email" con "mail@d"
        Y relleno "document" con "123456"
        Y selecciono "20" de "birthdate-day"
        Y selecciono "Diciembre" de "birthdate-month"
        Y selecciono "1998" de "birthdate-year"
        Y relleno "gender" con "Femenino"
        Cuando presiono "Guardar"
        Entonces debo ver "Por favor ingrese un mail válido"

    @javascript @createPlatformAndAccountAndOneUser
    Escenario: Editar un usuario con documento vacío y marcándolo como registrado.
        Dado espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
        Y sigo "GoIntegro Platform CI"
        Y espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".breadcrumb"
        Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
        Y hago click en ".more-options"
        Y sigo "Usuarios"
        Y espero a que aparezca el contenido dinámico "Listado de Usuarios" en ".backoffice-block"
        Y espero a que aparezca el contenido dinámico "Tyrion Lannister" en ".backgrid-user-list"
        Y hago click y sigo ".action-icon:first"
        Y espero a que aparezca el contenido dinámico "Editar usuario" en ".breadcrumb"
        Y espero a que aparezca el contenedor dinámico ".user-form .form-horizontal"
        Y relleno "email" con ""
        Y marco "registered"
        Cuando presiono "Guardar"
        Entonces debo ver "Un usuario registrado no puede tener el correo electrónico vacío"

    @javascript @createPlatformAndAccountAndOneUser
    Escenario: Editar un usuario con el documento vacío en una plataforma con unique field document
        Dado espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".string-cell"
        Y sigo "GoIntegro Platform CI"
        Y espero a que aparezca el contenido dinámico "GoIntegro Platform CI" en ".breadcrumb"
        Y espero a que aparezca el contenido dinámico "Administrar" en ".backoffice-header"
        Y hago click en ".more-options"
        Y sigo "Usuarios"
        Y espero a que aparezca el contenido dinámico "Listado de Usuarios" en ".backoffice-block"
        Y espero a que aparezca el contenido dinámico "Tyrion Lannister" en ".backgrid-user-list"
        Y hago click y sigo ".action-icon:first"
        Y espero a que aparezca el contenido dinámico "Editar usuario" en ".breadcrumb"
        Y espero a que aparezca el contenedor dinámico ".user-form .form-horizontal"
        Y marco "registered"
        Y relleno "document" con ""
        Cuando presiono "Guardar"
        Entonces debo ver "El documento no puede ser vacío porque es el campo único de la plataforma"