# language: es
Característica: Visualizacion de detalle de plataforma
  Como usuario del backoffice quiero poder ver el detalle de una plataforma

  Antecedentes:
    Dado estoy en "/backoffice/signin"
    Y relleno "_username" con "apibackofficetester"
    Y relleno "_password" con "apitesterbackoffice"
    Y presiono "_submit"

  @javascript @createAccountAndUserAndPlatform
  Escenario: Veo el detalle de una plataforma cuya cuenta no es hija de otra cuenta regional. Por ende tengo que poder visualizar los campos basicos y los de registracion/login y customizacion
    Dado estoy en "/backoffice/"
    Y sigo "ListAccounts"
    Y debe aparecer el contenido dinámico "GoIntegro Argentina - Test P" en ".string-cell"
    Y hago click en ".dropdown-toggle:first"
    Y sigo "btnListPlatformsFor"
    Y debe aparecer el contenido dinámico "Plataforma Test" en ".string-cell"
    Cuando sigo "Plataforma Test"
    Y espero a que aparezca el contenido dinámico "Plataforma Test" en ".backoffice-header"
    Y debo ver "Idiomas (3)" en el elemento ".backoffice-header"
    Y debo ver "Perfiles (3)" en el elemento ".backoffice-header"
    Y debo ver "Aplicaciones (0)" en el elemento ".backoffice-header"
    Y debo ver "Datos de la cuenta" en el elemento ".platform-account-information"
    Y debo ver "0-100" en el elemento "#usersRange"
    Y debo ver "Bodegas" en el elemento "#industry"
    Y debo ver "Configuración básica de la plataforma" en el elemento ".platform-basic-information"
    Y debo ver "No" en el elemento "#disable"
    Y debo ver "Plataforma Test" en el elemento "#name"
    Y debo ver "Argentina" en el elemento "#countriesSelected"
    Y debo ver "Español" en el elemento "#defaultLanguage"
    Y debo ver "UTC" en el elemento "#timeZone"
    Y debo ver "Si" en el elemento "#socialEnabled"
    Y debo ver "No" en el elemento "#socialNotificationsEnabled"
    Y debo ver "Gestión de almacenamiento" en el elemento ".platform-storage-information"
    Y debo ver "2048" en el elemento "#imageSize"
    Y debo ver "400" en el elemento "#videoSize"
    Y debo ver "204800" en el elemento "#storage"
    Y debo ver "Configuración de usuarios" en el elemento ".platform-user-information"
    Y debo ver "Empleado" en el elemento "#targetUserType"
    Y debo ver "Mostrar" en el elemento "#userVisibility"
    Y debo ver "ROLE_BASIC" en el elemento "#defaultRole"
    Y debo ver "No" en el elemento "#showUserEmail"
    Y debo ver "No" en el elemento "#usergroupEnabled"
    Y debo ver "No" en el elemento "#areasEnabled"
    Y debo ver "No" en el elemento "#hierarchyEnabled"
    Y debo ver "Configuración de beneficios" en el elemento ".platform-benefits-information"
    Y debo ver "No" en el elemento "#benefitsEnabled"
    Y debo ver "(sin imagen)" en el elemento "#logoBenefitsUrl"
    Y debo ver "No" en el elemento "#usesBenefitsCard"
    Y debo ver "No" en el elemento "#usesCoupon"
    Y debo ver "No" en el elemento "#benefitsPublic"
    Y debo ver "No" en el elemento "#rewardsEnabled"
    Y debo ver "Configuración de inicio de sesión y registro" en el elemento ".platform-signupSignin-information"
    Y debo ver "Si" en el elemento "#requireRegistration"
    Y debo ver "Si" en el elemento "#usesCard"
    Y debo ver "No" en el elemento "#isNominated"
    Y debo ver "Si" en el elemento "#usesBirthDate"
    Y debo ver "Si" en el elemento "#usesGender"
    Y debo ver "No" en el elemento "#requireVerification"
    Y debo ver "usernameId" en el elemento "#identityField"
    Y debo ver "Si" en el elemento "#hasPassword"
    Y debo ver "Si" en el elemento "#recoverPassword"
    Y debo ver "Texto para inicio de sesión" en el elemento ".platform-htmlLogin-information"
    Y debo ver "Personalización y customización de colores" en el elemento ".platform-customizations-information"
    Y debo ver "logoadidas.jpg" en el elemento "#logoUrl"
    Y debo ver "logoadidasfooter.jpg" en el elemento "#logoUrlFooter"
    Y debo ver "banner.jpg" en el elemento "#signinBannerUrl"
    Y debo ver "#AAAAAA" en el elemento "#defaultBackgroundColor"
    Y debo ver "#1888C8" en el elemento "#defaultBgColorHeaderFooter"
    Y debo ver "#FFFFFF" en el elemento "#defaultFontColor"
    Y debo ver "#FFFFFF" en el elemento "#buttonFontColor"
    Y debo ver "#106A91" en el elemento "#buttonBackgroundColor"
    Y debo ver "#106A91" en el elemento "#defaultBorderColor"
    Y debo ver "Términos y condiciones" en el elemento ".platform-termsAndConditions-information"
    Y debo ver "ROLE_ADMIN" en el elemento ".platform-roles"
    Y debo ver "ROLE_ADVANCED" en el elemento ".platform-roles"
    Y debo ver "ROLE_BASIC" en el elemento ".platform-roles"
    Y debo ver "English" en el elemento ".platform-languages"
    Y debo ver "Español" en el elemento ".platform-languages"
    Y debo ver "Português" en el elemento ".platform-languages"
    Y debo ver "No hay aplicaciones relacionadas" en el elemento ".platform-applications"

  @javascript @createRegionalAccountWithPlatform
    Escenario: Veo el detalle de una plataforma cuya cuenta es hija de otra cuenta regional. Por ende NO tengo que poder visualizar los campos basicos y los de registracion/login y customizacion
    Dado estoy en "/backoffice/"
    Y sigo "ListAccounts"
    Y debe aparecer el contenido dinámico "GoIntegro Argentina - Regional Child" en ".string-cell"
    Y hago click en ".dropdown-toggle:last"
    Y sigo "btnListPlatformsFor"
    Y espero a que aparezca el contenido dinámico "Plataforma Test" en ".string-cell"
    Cuando sigo "Plataforma Test"
    Y espero a que aparezca el contenido dinámico "GoIntegro Argentina - Regional Child" en ".breadcrumb"
    Y espero a que aparezca el contenido dinámico "Perfiles (3)" en ".backoffice-header"
    Y debo ver "Aplicaciones (0)" en el elemento ".backoffice-header"
    Y debo ver "Datos de la cuenta" en el elemento ".platform-account-information"
    Y debo ver "0-100" en el elemento "#usersRange"
    Y debo ver "Bodegas" en el elemento "#industry"
    Y debo ver "Configuración básica de la plataforma" en el elemento ".platform-basic-information"
    Y debo ver "No" en el elemento "#disable"
    Y debo ver "Plataforma Test" en el elemento "#name"
    Y debo ver "http://platform.ci.gointegro.net" en el elemento "#webSite"
    Y debo ver "Gestión de almacenamiento" en el elemento ".platform-storage-information"
    Y debo ver "800" en el elemento "#imageSize"
    Y debo ver "400" en el elemento "#videoSize"
    Y debo ver "2097152" en el elemento "#storage"
    Y no debo ver "Configuración de inicio de sesión y registro"
    Y no debo ver "Texto para inicio de sesión"
    Y no debo ver "Personalización y customización de colores"
